### ISSUE TITLE
Goto and From tags

### ISSUE THREAD

**Issue by Zangetsu-96** [aesim-tech/simba-project#113]
For larger circuits, too many wiring connections may make it difficult for the user to debug a problem. **Goto** and **From** tags just like the ones found in SIMULINK can be used in this case. This will not only help in easier debugging of the circuit but, also would help the design look cleaner.

**Comment by aesim-tech** [comment]
100% agree. This feature is already planned (#89) and will be available in 2021.02 or 2021.03.
