### ISSUE TITLE
Simulator crashes when trying to delete an existing single parameter sweep profile

### ISSUE THREAD

**Issue by Zangetsu-96** [aesim-tech/simba-project#115]
Let's say that you created a single parameter sweep profile in the test bench section and now, you want to delete it. As soon as you confirm by clicking "Yes" that you want to delete the profile, the simulator crashes.

**Comment by aesim-tech** [comment]
Thanks for reporting this ennoying bug. It has already been fixed and the fix will be available in the February release (#106 ).
