### ISSUE TITLE
draw the circuit diagram in the python api

### ISSUE THREAD

**Issue by isablanca** [aesim-tech/simba-project#122]
The software has python API for circuit design. It could be convenient to check the correctness of the script if we have a function to visualize the circuit script, for example, provide a circuit diagram like the canvas of the main Simba program.

**Comment by aesim-tech** [comment]
This feature would be nice. If we include the Shape/Symbol interface in the Public Python API, Would you be interested to build the Python code that draw circuits ?

**Comment by aesim-tech** [comment]
Closed in favour or #55
