### ISSUE TITLE
THD and Power measurement

### ISSUE THREAD

**Issue by aesim-tech** [aesim-tech/simba-project#137]
**Power (1ph and 3ph)**
- [x] Instantaneous Power P
- [x] Active Power P
- [x] Reactive Power Q
- [x] Apparent Power S
- [x] Power Factor PF

**Power Quality**
- [x] THD Control measurement block
- [x] RMS Control measurement block

**Misc**
- [x] Tests
- [x] Documentation (Including Equations)

**Comment by jerome-secretgit** [comment]
RMS Control measurement block

![Image](https://github.com/aesim-tech/simba-project/assets/114773624/bbaecf92-d856-4b4c-a71c-de4f9629afdf)

Solver implemented
Test added --> ok at 0.01%

**Comment by jerome-secretgit** [comment]
THD control measurement block

![Image](https://github.com/aesim-tech/simba-project/assets/114773624/68058107-6264-488f-a53f-bf7d94a8ca4f)

THD definition:
![Image](https://github.com/aesim-tech/simba-project/assets/114773624/f681c84a-1048-4d5d-8ddb-9dda9c028e88)
--> we will consider the THD-F : ratio on the fundamental
 THD = (IRMS - I1) / I1

Parseval criteria
![Image](https://github.com/aesim-tech/simba-project/assets/114773624/025e953a-9268-4330-81a1-2c7244ce3978)

**Comment by jerome-secretgit** [comment]
![Image](https://github.com/aesim-tech/simba-project/assets/114773624/0062dbda-2d0a-49b4-85b4-b9be42bf0117)

- Puissance réelle/active P : Intégrale de 0 à T de v(t).i(t).dt
- Puissance réactive Q : U1.I1.Sin(Phi1) (ne comprend pas la puissance déformante)
- Puissance Apparente S : URMS.IRMS

**Comment by manu-aesim** [comment]
Do we want to have access to "RMS Current" and "RMS Voltage" in all the devices ? (using the new "Base Frequency" settings).

**Comment by jcornau** [comment]
RMS device : symbol OK & solver OK --> validated
THD device : symbol OK & solver OK --> validated
Power Probe : symbols OK & solver OK --> validated
Power Probe 3Phases : symbols OK & solver OK --> validated


![Image](https://github.com/aesim-tech/simba-project/assets/22816127/c9a9ee47-c5be-4f91-9178-4adcb8ae0bb3)
