### ISSUE TITLE
Subcircuit Variables

### ISSUE THREAD

**Issue by aesim-tech** [aesim-tech/simba-project#159]
- [ ] Add an option to define variables at the sub-circuit level. 
- [ ] Multiple instances of the same sub-circuit can have different variable values.
- [ ] If a sub-circuit cannot find a variable value in its definition, it will try its higher levels in the hierarchical order until it reaches the top circuit.
- [ ] If a subicircuit can't find a variable value in its definition or in its hierarchy, an error will be thrown.
- [ ] Subcircuit variables are accessible and modifiable via the Python API.

**Comment by ghost** [comment]
For the first item "Add an option to define variables at the sub-circuit level" do you mean this?

--> consider to implement some kind of mask to access the inside parameters of the subsystem without the need of opening said subsystem. ??

**Comment by manu-aesim** [comment]
> For the first item "Add an option to define variables at the sub-circuit level" do you mean this?
> 
> --> consider to implement some kind of mask to access the inside parameters of the subsystem without the need of opening said subsystem. ??

Yes, if you check out the latest beta version, you can define variables on the subsystem and use these variables in the subsystem content.

**Comment by ghost** [comment]
Ah yes, right !! thanks Manu ! (I just tested right now) !!
