### ISSUE TITLE
Mosfet reverse conduction and switching loss

### ISSUE THREAD

**Issue by guillaumefontes** [aesim-tech/simba-project#175]
* if conduction loss data are not provided for i < 0, consider same loss with: vdrop(abs(i)) (that's already the case in Simba)
* if switching loss data are not provided for i < 0, consider Esw = 0 (assume body diode switching loss can be neglected)

**Comment by aesim-tech** [comment]
It was decided to clamp switching losses to 0 for negative current if data are not provided for i < 0.
