### ISSUE TITLE
Double-click Support

### ISSUE THREAD

**Issue by manu-aesim** [aesim-tech/simba-project#230]
**Is your feature request related to a problem? Please describe.**
One user made the following comment: "_I keep trying to double click subcircuits to go into them but then I remember I have to click them and then click “open”. This adds additional friction that makes the process feel more cumbersome._"

**Describe the solution you'd like**
When a user double-clicks on a subcircuit or a block of C code, it should have the same effect as clicking on "Open" or "Edit".

**Comment by jpellegrinopws** [comment]
PR https://github.com/aesim-tech/simba/pull/90
