### ISSUE TITLE
Import xml thermal data file: scale of switching energies not taken into account

### ISSUE THREAD

**Issue by guillaumefontes** [aesim-tech/simba-project#235]
When importing a xml thermal data file, the scale of the switching energies are not taken into account to fill the tables (for example 'mJ').

**Comment by guillaumefontes** [comment]
It seems the problem is remaining.
![image](https://user-images.githubusercontent.com/28732566/235311510-eaaac66b-78c0-4921-9f82-b6fd799e7e68.png)

Example with this file:
[C2M0025120D.zip](https://github.com/aesim-tech/simba-project/files/11359565/C2M0025120D.zip)

**Comment by manu-aesim** [comment]
We had a problem with thermal data localization. That's why it was working on my computer and not yours. It is now fixed with the latest version (2023.05.01).
