### ISSUE TITLE
Import .csv and .txt signals data

### ISSUE THREAD

**Issue by manu-aesim** [aesim-tech/simba-project#236]
**Is your feature request related to a problem? Please describe.**
Many users requested the capability to import .csv and .txt files in the results tab of SIMBA in order to compare results with SIMBA results. 

**Describe the solution you'd like**
We could add a "3 dots" button right next to the search bar on the Result tab with an "Import..." option. This import option will open an "Open-File" dialog box that can be used to select TSB and CSV files. Two formats should be supported: 
- Single time axis: The first column is the X-axis data and all other columns refer to the same X-axis data.
- Multiple time axis: Each even column is x-axis data and each odd column is signal data (y-axis).

**Comment by jcornau** [comment]
Code finished and PR done
Need to add documentation
