### ISSUE TITLE
Scope signal data compression

### ISSUE THREAD

**Issue by manu-aesim** [aesim-tech/simba-project#241]
**Is your feature request related to a problem? Please describe.**

* Between two discontinuity events, SIMBA always calculates at least 4 points to ensure that we simulate all time constants.  These points are saved in the scopes but may not carry any additional information. 

**Describe your desired solution**.
We need to consider whether we can remove these points from the scopes. A simple option would be that if the LTE (local truncation error) calculated on these points is low (1E-8?), to remove these points from the scopes. 

**Steps:**
- [x] 1. Build a compression algorithm that Remove points without information and add Transient analysis settings: "Compress scopes"
- [x] 2. When the option is selected, stop sharing the time data vector with all scopes. Every scope must have its own time data vector
- [x] 3. Use the compression algorithm on each individual scope. 
- [x] 4. Analyze performance impacts (Memory/Number of points and speed)
- [x] 5. Update Documentation

**Comment by jcornau** [comment]
Performance
|                        | No Compression | Compressed @1e-5 | Delta |
|------------------------|--------------------|---------------------|-------|
| Fixed time step        |                    |                     |       |
| Number of points         | 21 233 721         | 3 845 254           | -82%  |
| Time                  | 15132 ms           | 16816 ms            | 11%   |
| Variable time step     |                    |                     |       |
| Number of points         | 5 152 435          | 1 617 828           | -69%  |
| Time                  | 4131 ms            | 4290 ms             | 4%    |

**Comment by manu-aesim** [comment]
- [ ] Update Doc

**Comment by manu-aesim** [comment]
**Preview version:** 

https://aesimtech.s3.us-east-1.amazonaws.com/artifacts/R2planF4ytgohfyH0944X3VL8gBoYjB3/simba.exe
pip install aesim.simba==2024.4.22a1

**Comment by manu-aesim** [comment]
**doc**

Scope compression is a feature designed to optimize memory usage. This feature is particularly useful in scenarios where simulations generate a large number of points. This option is available in the simulation settings panel and is disabled by default.

<img src="https://github.com/aesim-tech/simba-project/assets/112709259/708d986a-9ca9-49e6-82a5-8c2d7151feea" width="200" >

When a simulation is running, Simba solver will apply an algorithm to calculate the variation between consecutive points. If the relative variation is not significant (relative error lower than 1e-5), the point will not be saved in the scopes. Activate this option can drastically reduce the memory size of the simulation and the time to load the simulation results in the GUI.

**Note :** 
Sampled signals (when "Sampling time" is defined) are not affected by the compression.

<img src="https://github.com/aesim-tech/simba-project/assets/112709259/63d79056-8b25-4c33-a204-4c54007c0a87" width="300" >


In yellow : no compression
In blue : with compression
