### ISSUE TITLE
Fix Thermal Data documentation 

### ISSUE THREAD

**Issue by manu-aesim** [aesim-tech/simba-project#248]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/112709259/223729124-06d186aa-380b-464e-87b4-fbe1e1815083.png)

There is an error in this picture on the Foster chain. It is impossible to connect a Foster network to a Cauer network (heat sink) as shown in the figure. It is necessary to connect a cauer network with another cauer or a Foster network with a Foster network. But do not mix the two as shown here.

**Describe the solution you'd like**
We should fix the image.

**Comment by guillaumefontes** [comment]
Here is a new proposition:

![image](https://user-images.githubusercontent.com/28732566/230366110-11161f3b-fc3c-45eb-be87-1250d9eb89cf.png)

[figures_cauer_foster_networks.pptx](https://github.com/aesim-tech/simba-project/files/11170146/figures_cauer_foster_networks.pptx)
