### ISSUE TITLE
Control Model: C Code

### ISSUE THREAD

**Issue by aesim-tech** [aesim-tech/simba-project#26]
- [x] Embed C Compiler (MinGW ?)
- [x] New C Code block 
- [ ] Documentation
- [ ] Ability to Debug C Code

**Comment by physicboy** [comment]
if possible can add discrete sampling time functionality and add sampling delay effect to the C block...thus it can better mimic realistic discrete controller(MCU)

**Comment by aesim-tech** [comment]
> if possible can add discrete sampling time functionality and add sampling delay effect to the C block...thus it can better mimic realistic discrete controller(MCU)

It is totally possible. I might also add another block that simply sample a signal at a fixed rate. This is helpful not only for C Code block
