### ISSUE TITLE
MOSFET with Diode

### ISSUE THREAD

**Issue by manu-aesim** [aesim-tech/simba-project#263]
Ideal MOSFET Model with an anti-parrallel Diode.

**Comment by physicboy** [comment]
How about IGBT model? with an ideal diode and voltage drop on the forward conduction path?

**Comment by manu-aesim** [comment]
It's very easy to do. I just created an issue for the next release: https://github.com/aesim-tech/simba-project/issues/264

The reason why we have added the 'MOSFET with diode' first is to stay compliant with the latest update of the Thermal Description file format.
