### ISSUE TITLE
C Code block inside a subcircuit is not sampled

### ISSUE THREAD

**Issue by lat-kar** [aesim-tech/simba-project#268]
If a C Code block is placed inside a subcircuit, it's not sampled.

**Comment by manu-aesim** [comment]
Thanks for noticing the bug. I think I have fixed it :
https://aesimtech.s3.amazonaws.com/artifacts/JjVaPm3Cx24J6QcN9bVEy2vGzKn9UTfr/simba.exe

I have quickly tested but can you please double check ? If yes, I will
publish a new version.

Thanks,
Manu.

**Comment by lat-kar** [comment]
Yeah, that seems to have fixed the problem.
