### ISSUE TITLE
New Parameter "Additional Include Directory" to the "C Code" Model

### ISSUE THREAD

**Issue by manu-aesim** [aesim-tech/simba-project#279]
**Feature Request:**

In response to users' need to utilize multiple C code files with the "C Code" model, we're proposing a new parameter: "Additional Include Directory". This parameter would enhance flexibility, allowing for easier testing of microcontroller code.

**Proposed Solution:**

By integrating this parameter, users will be able to specify additional directories with code to be included. It will function as an extension to the "-I" parameter of the GCC compiler (see reference [here](https://www.rapidtables.com/code/linux/gcc/gcc-i.html)).

We're looking forward to feedback on this proposed solution. Please feel free to share any thoughts or additional suggestions you might have.

![Image](https://github.com/aesim-tech/simba-project/assets/112709259/12541009-7bb5-42c6-a943-68b8f40a82d8)

**Comment by manu-aesim** [comment]
Beta version: https://aesimtech.s3.amazonaws.com/artifacts/zZnoYa5u3aBEBNWALW97W29WPyzdQGHf/simba.exe

**Comment by physicboy** [comment]
Hi Manu,

Do you consider to implement this function to use simba to call the compiler for all C-code/header file.
Perhaps by providing the directory of the code files and the main file

I think for me it will be a little confusing if one file is embedded inside Simba file and other files are in separate folder

**Comment by manu-aesim** [comment]
> Hi Manu,
> 
> Do you consider to implement this function to use simba to call the compiler for all C-code/header file. Perhaps by providing the directory of the code files and the main file
> 
> I think for me it will be a little confusing if one file is embedded inside Simba file and other files are in separate folder


Hi Arief,
Not sure to understand. You can also use the "C Code" External File to have all the C Code into the same directory and nothing in SIMBA.

**Comment by physicboy** [comment]
Hi Manu....

Yes...that makes a lot more sense

Thanks for your answer
Arief
