### ISSUE TITLE
Design Example.Buck_Thermal() in Python module

### ISSUE THREAD

**Issue by guillaumefontes** [aesim-tech/simba-project#280]
`design = DesignExamples.Buck_Thermal()`

 returns a *System.ValueTuple[Design,List[ThermalData]] object*

instead of a *Simba.Data.Design object*

in python module version 2023.5.19

**Comment by manu-aesim** [comment]
Hi Guillaume,

I agree this is a bit strange but this is not really a bug. This is because this tuple contains the design and the list of thermal data used in it.

Here is how to access the design:

```python
design = DesignExamples.Buck_Thermal().Item1
```

Anyway, I have changed the behavior and Buck_thermal() will return a Design starting next version
