### ISSUE TITLE
Bizzare C-code behavior

### ISSUE THREAD

**Issue by physicboy** [aesim-tech/simba-project#292]
Hi teams,

I today experience sudden crash, and the C-code suddenly replaced with default C-code template after re-opening the simulation file

I dont know how to replicate the issue, but it just happened

Thanks,
Arief,

**Comment by manu-aesim** [comment]
Hi Arief, 

Have you checked the backup file if it contained the C Code ? 

I will have a look. to this but it is hard for me to debug if we can't reproduce the issue.

Thanks,
Manu.

**Comment by physicboy** [comment]
Hi Manu,

I cant find any file in the backup folder.

I will send you the simulation model in question via email.

Thanks,
Arief,

**Comment by manu-aesim** [comment]
I will close that issue for now but let me know if it happens again please.
