### ISSUE TITLE
Thermal models with "Formula only" computation method, won't allow simulation to go past initialization stage

### ISSUE THREAD

**Issue by lat-kar** [aesim-tech/simba-project#298]
If a semiconductor switch is assigned with thermal data where "Formula only" computation method is used, SIMBA will indefinitely run the initialization phase. 
![image](https://github.com/aesim-tech/simba-project/assets/129766842/de1af657-9859-43f9-9225-2030f2ac549e)

To reproduce this problem: [here](https://github.com/aesim-tech/simba-project/files/11875326/Infineon-IGBT_1200V.zip) you can find the package of IGBT transistors I tested that cause this error.

**Comment by manu-aesim** [comment]
@karol-aesim , kan you please checked that this is fixed in the latest beta? 
Thanks !

**Comment by lat-kar** [comment]
Hey Manu, 

I checked and it looks like this error has been fixed in the latest beta version. Thanks!
