### ISSUE TITLE
Save/Pause

### ISSUE THREAD

**Issue by vishal240294** [aesim-tech/simba-project#300]
A few customers has requested the save and pause feature for SIMBA.

**Comment by manu-aesim** [comment]
What do you mean by Save ?

**Comment by vishal240294** [comment]
Pause a simulation and save data. This request was asked by National Physical Oceanography Laboratory.
![image](https://github.com/aesim-tech/simba-project/assets/15937535/f84203e8-8f18-4152-bc26-1597f093cdcc)
