### ISSUE TITLE
Unable to open Simba File 

### ISSUE THREAD

**Issue by vishal240294** [aesim-tech/simba-project#303]
On user reported in follow-up, when he want to open a project double click only the SIMBA page opened instead of opening project. We suggested using an open project. But, as said in other software it opens the file.

**Comment by physicboy** [comment]
it happens to me all the time

I just wasnt bothered to report it

**Comment by vishal240294** [comment]
@physicboy  it is fixed now.

**Comment by vishal240294** [comment]
Fixed in August  release.
