### ISSUE TITLE
Python Example 5 (parallel parameter sweep) with pre-release aesim.simba 2023.6.29a1

### ISSUE THREAD

**Issue by guillaumefontes** [aesim-tech/simba-project#308]
**With pre-release of the python library**
Spikes on *Vout vs duty cycle* graph.

![image](https://github.com/aesim-tech/simba-project/assets/28732566/b1c499a0-4603-4207-a3cd-b11f1764b8f8)
 
** Which does not appear with official release of May **

![image](https://github.com/aesim-tech/simba-project/assets/28732566/d0547b1b-9f08-45c8-9608-9f9943c83b57)

**Comment by manu-aesim** [comment]
This one is fixed. Some of the simulations were throwing errors because of a random bug related to the OTSF.
