### ISSUE TITLE
new models/features to be added

### ISSUE THREAD

**Issue by ghost** [aesim-tech/simba-project#312]
It would be good to add:

- Three-phase models (diodes, R/L/C branches, V/A sources, phase voltage/current meter) for easier usage when building three-phase models
- min and max function block (but only available in result tab)
- arc function block
- Transforms blocks: Stokvis/Fortesque (direct, inverse and zero sequence) 
- Cursor line too thick into the result tab
- Option to plot (after simulation is complete) a math function using result signals
- create a log file if SIMBA crashes suddenly
- Option to detach the results on separate window
- When locking two (or more) different charts, the Y scales are locked too, so it isn’t practical to zoom in charts with scales too different.

**Comment by manu-aesim** [comment]
We should create multiple issues instead of one with unrelated topics. Some of the requests are already in our backlog.
