### ISSUE TITLE
Impossible to assign one .XML description of a diode

### ISSUE THREAD

**Issue by guillaumefontes** [aesim-tech/simba-project#313]
Found a description of a diode (which uses formula and custom variables) which leads to a crash.
IKW50N120CS7

1. The thermal description can be created with the .XML file importation,
2. When we try to assign this thermal description to a diode, Simba crashes.

It seems to have a link with the custom variable 'Rg'. Indeed if this last one is deleted, the assignation does not crashes anymore.

![image](https://github.com/aesim-tech/simba-project/assets/28732566/07519746-d951-4a41-9bfc-3af771e906a3)

[IKW50N120CS7.zip](https://github.com/aesim-tech/simba-project/files/12147362/IKW50N120CS7.zip)

**Comment by manu-aesim** [comment]
Thanks for the issue. This is now fixed.

The error was due to one custom table that was not working properly in our interpolator.
