### ISSUE TITLE
Cursor line width

### ISSUE THREAD

**Issue by ghost** [aesim-tech/simba-project#317]
In the "result" tab, it would be good to have the capability to play with the width of Cursor line.
It is too thick.

**Comment by manu-aesim** [comment]
I never saw a case where the width of the cursor were too thin or too thick. Would it be possible to share a screenshot of such a case? In any case, we will recode entirely the chart engine soon.

**Comment by ghost** [comment]
I don't have a case showing this but this is only the feedback of one user:  • Cursor line too thick. 
So I was wondering if a new "parameter" window could be added in "result" tab in order to play with the width of the cursor (see attached) and font/size of label (vertical axis)
<img width="1009" alt="cursor_line" src="https://github.com/aesim-tech/simba-project/assets/115028249/6587534f-6aa5-4c65-9184-eacb8c918ddc">

**Comment by manu-aesim** [comment]
Thanks but I'm not sure about the added value for the user.

**Comment by ghost** [comment]
"more customization"  but I do agree with you.
