### ISSUE TITLE
Incorrect result of a thyristor bridge with a star/star transformer using the multi-time-step solver

### ISSUE THREAD

**Issue by jcornau** [aesim-tech/simba-project#324]
**Describe the bug**
A simulation with a thyristor bridge and a star/star transformer is giving wrong results at specific time points when using the multi-time-step solver. 

It seams some commutations of the diods are not expected. The differences can also vary when changing the circuit (using a different grid frequency) or the simulation settings (different minimal time step).

**Screenshots**
![image](https://github.com/aesim-tech/simba-project/assets/22816127/0e5118fc-077a-43fa-af54-fcb37bb2ec10)

**Desktop**
 - OS: Windows 11
 - Language: Any

**SIMBA Version**
 - Version 2023.08 & 2023.05

**Comment by manu-aesim** [comment]
@jcornau , I think it is now fixed and the test is added to the CI pipeline. Can you please double check the original file causing the issue with the latest beta release ?

**Comment by jcornau** [comment]
@manu-aesim 
I checked with the original model and the problem is fixed in both cases:
- predictive time step and Sampling time activated,
- fixed time step solver.

![image](https://github.com/aesim-tech/simba-project/assets/22816127/1e40d182-2b54-4c01-abae-e54110b4ff4f)
