### ISSUE TITLE
Control PWL sources being compromised by connector labels

### ISSUE THREAD

**Issue by rcmartins72** [aesim-tech/simba-project#327]
**Describe the bug**
Connector labels sometimes seem to disrupt the PWL source they are connected to - the connectors still seem to do their job of tying nets "over the air". The problem is that weirdly the source to which they were attached "forgest" its custom waveform.
I had initially a set of 5 PWL control sources each individually configured to a specific TimeValueMatrix using Python
All had connector labels connected to them.
If they only have connector labels connected to them everything works fine. However, when those connector labels then go on to connect to other control blocks that implement other operations then, for some reason, and rather randomly (meaning, not quite figured out the mechanism) the original PWL defaults to the original waveform. This seems to happen when the PWL are connected to a control-product operator. If instead of connecting through the labels I connect with "wires" then everything seems to work fine again, but obviously the legibility brought in by the labels is lost and the GUI becomes closer to the, to me dreadfull, LabView, kind of "coding".

UPDATE: I've just added new connector labels to the PWL sources, i.e., after the rest of the control circuit in place and renamed where appropriate and it started working as expected.
Would say this is a minor bug, but still can catch people unaware.

**To Reproduce**
1. Create PWL sources (control) and replace their TimeValueMatrix with a matrix (numpy to list)
2. Connect two of these to a math product operator
3. Create a few of these blocks and plot the PWL output

**Expected behavior**
The PWL that have not been connected to a product operator will still show the custom waveform. The ones connected to the product will have lost their custom waveform and defaulted to the original one.

**Screenshots**
![image](https://github.com/aesim-tech/simba-project/assets/141913282/baab60bf-982c-424f-ad2c-c1169fa5336c)
![image](https://github.com/aesim-tech/simba-project/assets/141913282/a7e4a9e0-9d03-4b9b-8a20-99383a032691)

**Desktop (please complete the following information):**
 - OS :Windows 10
 - Language: Python

** SIMBA Version**
 - Version 23.5.5.0

**Comment by manu-aesim** [comment]
Hello,

Would you mind sharing the python script causing the issue and/or the resulting simba project file that is not working properly ? 
Without this it is hard to understand exactly what is going on.  I've seen similar problems caused by label names: to work properly, label names must be perfectly identical (with no extra spaces and the same case). 

If it contains confidential data, you can mail it to me at manu@aesim.tech.

**Comment by manu-aesim** [comment]
Problem solved outside of Github.
