### ISSUE TITLE
The "hierarchical" bar disappears when you press ctrl+z in a subcircuit

### ISSUE THREAD

**Issue by jcornau** [aesim-tech/simba-project#328]
**Describe the bug**
The "hierarchical" bar disappears when you are in a subcircuit and you press ctrl+z. It can be difficult to go back in the upper circuit. 

**To Reproduce**
1. Enter inside a subcircuit
2. Move something (a device, a signal)
3. Enter inside a subcircuit in this subcircuit
4. Press Ctrl+Z
5. it goes back to the first subcircuit but the bar is no more there

**Expected behavior**
The "hierarchical" bar should stay on the top of the screen.

**Screenshots**
![image](https://github.com/aesim-tech/simba-project/assets/22816127/453bab88-cbc2-45fa-87ca-7a839e8cf1b0)

after ctrl+Z

![image](https://github.com/aesim-tech/simba-project/assets/22816127/68a7ab44-7b54-4ce8-bc10-f1337e49e2e7)

**Desktop:**
 - OS: Windows 11
 - Language: English

**SIMBA Version**
 - Version 23.8.2.0

**Comment by jpellegrinopws** [comment]
PR 134
https://github.com/aesim-tech/simba/pull/134
