### ISSUE TITLE
Controlled Current Source : error when using in the Dc Dc Buck Converter

### ISSUE THREAD

**Issue by jcornau** [aesim-tech/simba-project#339]
**Describe the bug**
In some cases, the current of the Controlled Current Source is not following correctly the control input of the device. At some points, it is coming back to 0. 

**To Reproduce**
using the Dc Dc Buck Converter
1. Open the Dc Dc Buck converter example model
2. measure the current of the inductor with a probe and send it to a controlled current source
3. Compare the scopes "in" and "currents" of the controlled current source --> the current waveform is not following the in waveform.

![image](https://github.com/aesim-tech/simba-project/assets/22816127/9474f10f-cd07-4ac7-a66f-3abaec410675)

![image](https://github.com/aesim-tech/simba-project/assets/22816127/83def6e1-94a2-47e1-beb7-33e99da0c4ef)

**Expected behavior**
The Current waveform should follow the "in" scope.

**SIMBA Version**
Version 23.08.23.0

**Comment by manu-aesim** [comment]
This bug was caused to an "iteration" delay between the power and control solvers. This bug is now fixed. 

https://aesimtech.s3.us-east-1.amazonaws.com/artifacts/AeCrxoW3vjiMF3wakZNSLJSalO2bGwVO/simba.exe
