### ISSUE TITLE
Possible bug with ZOH and fixed time-step

### ISSUE THREAD

**Issue by guillaumefontes** [aesim-tech/simba-project#341]
Example with a sine source @50Hz with a probe.
Let's try to sample the output of this probe at 1e-3s.

With predictive time-step, it is OK.
With fixed time-step @1e-7s, it gives strange values for the first periods of the sine.

![image](https://github.com/aesim-tech/simba-project/assets/28732566/be7fd90a-a5dc-4251-ad32-019a783754f5)

You can find simulation file below. Results considered with beta version of 14-09.
[possible-bug-zoh.zip](https://github.com/aesim-tech/simba-project/files/12771311/possible-bug-zoh.zip)

BR

**Comment by manu-aesim** [comment]
This bug was caused by a numerical rounding error and should be solved in this release:

https://aesimtech.s3.us-east-1.amazonaws.com/artifacts/AeCrxoW3vjiMF3wakZNSLJSalO2bGwVO/simba.exe
