### ISSUE TITLE
subcircuit cannot include "ac sweep perturbation" block

### ISSUE THREAD

**Issue by ghost** [aesim-tech/simba-project#343]
**Describe the bug**
An "ac sweep perturbation" block  could not be encapsulated into a subcircuit: there is an error message shown when simulating " perturbation device not found"! 

**To Reproduce**
See the attached gif file to reproduce the issue
![bug2](https://github.com/aesim-tech/simba-project/assets/115028249/bb4e172a-cee6-4508-9925-17dd97aba8ff)

**Comment by manu-aesim** [comment]
This is not really a bug but a limitation. The AC Sweep perturbation must be in the top circuit. 

We will add it to the documentation and improve the error message.

**Comment by ghost** [comment]
Thanks Manu, I see !

**Comment by jcornau** [comment]
I updated the documentation (device doc and AC Sweep functionnality doc).

**Comment by ghost** [comment]
Thanks Jérome !
