### ISSUE TITLE
Undo/Redo: Corrupted subcircuit stack

### ISSUE THREAD

**Issue by manu-aesim** [aesim-tech/simba-project#348]
**Describe the bug**
The "hierarchical" bar disappears when you are in reverting a change that happened in a  subcircuit.

**To Reproduce**

- Enter inside a subcircuit
- Move something (a device, a signal)
- Go to another design
- Press Ctrl+Z
- it goes back to the subcircuit but the bar is no more there

**Expected behavior**
The "hierarchical" bar should stay on the top of the screen.

**Comment by aesim-jeromep-secretgit** [comment]
PR : https://github.com/aesim-tech/simba/pull/145

**Comment by jpellegrinopws** [comment]
Maybe the ticket can be closed ? @manu-aesim
