### ISSUE TITLE
Bug display with "Text" block

### ISSUE THREAD

**Issue by ghost** [aesim-tech/simba-project#361]
If you add a "text" block into the design and write "hello, how are you"?
the format is good but when you close the design and re open it: it will be shown like this:

![text](https://github.com/aesim-tech/simba-project/assets/115028249/d37fdef5-42c2-48a6-ad90-f935b86bc2a7)

**Comment by jpellegrinopws** [comment]
PR 167
https://github.com/aesim-tech/simba/pull/167
