### ISSUE TITLE
Option to make subcircuit unique

### ISSUE THREAD

**Issue by ghost** [aesim-tech/simba-project#363]
When we create a subcircuit into SIMBA and if we duplicate it several times and if we modify one value of one parameter inside the subcircuit, all the values of the same parameter will be modified for the other subcircuits.

Is it possible to avoid to liaised all the subcircuits when modifying any parameters?

to sum up : all the subcircuits must operate separately (without using the design variables window)

Thanks,
KR,

**Comment by manu-aesim** [comment]
In SIMBA 24.09, when a subcircuit is instantiated more than once, the list of subcircuit instances appears in the device property panel. If one of those subcircuits is modified, all subcircuits are also modified. 
To make an instance unique (independent from the others), a new "Make Unique" button is available.

https://github.com/user-attachments/assets/9e5cf3da-1d34-4610-b5ae-5dcf2b2875ff
