### ISSUE TITLE
AC Sweep data is exported to an empty spreadsheet

### ISSUE THREAD

**Issue by lat-kar** [aesim-tech/simba-project#379]
When we export AC Sweep results to a .csv file, SIMBA exports an empty spreadsheet.

![image](https://github.com/aesim-tech/simba-project/assets/129766842/00efc139-b6a1-4ff4-8f26-ba546166b019)

Another small thing: The phase unit has an A letter with a circumflex accent in the brackets: [Â°]

**SIMBA Version 23.11.30**

**Comment by jcornau** [comment]
Bug has been fixed, now frequency points are saved in the CSV, even when mixed results are used (time points and frequency points).
