### ISSUE TITLE
When the signal is sampled, the cursors do not display any values

### ISSUE THREAD

**Issue by lat-kar** [aesim-tech/simba-project#380]
**Describe the bug**
When we sample our signal, the cursors in the Result tab don't show any values except X1 and X2. 

![image](https://github.com/aesim-tech/simba-project/assets/129766842/2f5b1b6f-e128-4263-a925-af1c7ae20154)

**Expected behavior**
I'd expect cursors to be able to measure all values or at least show basic values like Y as well as ΔX and ΔY.

**Comment by jcornau** [comment]
A second issue has been fixed in the same time : the interpolated value for sampled signals were not good.
