### ISSUE TITLE
Undo H-zoom with multiple locked charts

### ISSUE THREAD

**Issue by guillaumefontes** [aesim-tech/simba-project#411]
When I want to "undo" an horizontal zoom with two locked charts, it only affects the first graph.

For example:

1. lock the 2 graphs
2. perform an horizontal zoom
3. click "undo"

Now, to solve this, I found a small trick: I redo another zoom to re-synchronize the charts.

More details in this video.
https://github.com/aesim-tech/simba-project/assets/28732566/8991d22d-186c-4923-9700-79128a6f01ed

**Comment by manu-aesim** [comment]
@jcornau ,

Do you think you can take care of this? I think we simply need to propagate the undo call to all synced charts. 

Thanks!
