### ISSUE TITLE
Export data (.csv file) from a DFT chart 

### ISSUE THREAD

**Issue by guillaumefontes** [aesim-tech/simba-project#412]
When I try to export data (with a .csv file) from the chart which displays the DFT results, it returns an empty file.

**Comment by manu-aesim** [comment]
@jcornau , 
this is fixed in the dev branch, right ?

**Comment by jcornau** [comment]
@manu-aesim,
No, dev has the fix for the AC SWEEP results. 
I just added another part for DFT results we have to validate.
