### ISSUE TITLE
Controlled Speed Source

### ISSUE THREAD

**Issue by guillaumefontes** [aesim-tech/simba-project#416]
As a user, I would like to get a controlled speed source to model loads that impose a speed. This speed can depend on a custom function (computed with control blocks or from a C-code), or can be read from a .csv file for example to apply a "speed profile".

**Comment by manu-aesim** [comment]
This is quite simple to implement. Since this is a user request, we will prioritize this.

**Comment by imaryoko** [comment]
Hi, I implemented controlled speed. Here's GUI.
![image](https://github.com/aesim-tech/simba-project/assets/113622535/c202df2e-2c6a-4fa4-beef-06816c7663cb)

**Comment by manu-aesim** [comment]
Thanks Ryoko!

https://aesimtech.s3.us-east-1.amazonaws.com/artifacts/ybPnxOAweYqNEhwYgEtFLJ5ZijNVERX7/simba.exe
pip install aesim.simba==2024.4.5a1

**Comment by ghost** [comment]
Do you plan to add an "out" scope for this new block?
Actually only "in" scope is mentioned.

**Comment by manu-aesim** [comment]
@AdriPWS ,
Why do you think we need it? It should be the same value, isn't it?

**Comment by ghost** [comment]
Yes, it should the same I agree, but for python manipulation, if people want to manipulate output data without adding a probe?
Just my idea :) !

**Comment by manu-aesim** [comment]
I don't understand. They can still use the "In" probe, isn't ?

**Comment by ghost** [comment]
ahah yes, they can but I assume MAYBE they will ask " why the output is not available"?
We can let like this and see later, no issue.
