### ISSUE TITLE
Error when loading .xml files

### ISSUE THREAD

**Issue by ghost** [aesim-tech/simba-project#418]
Those 2 xml files attached failed to be opened for thermal analysis
[CGD65A055S2.xml.txt](https://github.com/aesim-tech/simba-project/files/14947436/CGD65A055S2.xml.txt)
[GS66516.xml.txt](https://github.com/aesim-tech/simba-project/files/14947437/GS66516.xml.txt)

Below the error received when trying to load them:
![error_thermal](https://github.com/aesim-tech/simba-project/assets/115028249/1b56e5aa-d48f-407f-a9d8-6684bebe79cc)

Thanks

**Comment by manu-aesim** [comment]
This was caused by some irregularities in the XML files. I have fixed this in this preview version: 

https://aesimtech.s3.us-east-1.amazonaws.com/artifacts/d6jTLKKahrTohwledsUHsgghndj3AizB/simba.exe
pip install aesim.simba==2024.4.11a1
