### ISSUE TITLE
Import and read SPICE netlist 

### ISSUE THREAD

**Issue by ghost** [aesim-tech/simba-project#419]
As a user I would like to have the possibility to read spice netlist (.cir) including :

- [x] Resistor (.R)
- [x] Inductor (.L)
- [x] Coupled Inductors (.K)
- [x] DC/AC Voltage/Current Sources (.V .I)
- [x] CCCS/CCVS (.F .H)
- [x] Subcircuits  (.SUBCKT .ENDS)
- [x] Scopes (.SAVE) 

**Progress:**
- [x] Spice Netlist Parser Development
- [x] Test
- [x] User Interface
- [x] Documentation

**Comment by jcornau** [comment]
After an analyse of the code, the following tokens are taken into account :

- [x] Resistor (.R)
- [x] Inductor (.L)
- [x] Coupled Inductors (.K)
- [x] DC/AC Voltage/Current Sources (.V .I)
- [x] CCCS/CCVS (.F .H)
- [x] Subcircuits (.SUBCKT .ENDS)
- [x] Scopes (.SAVE)

and :
- [x] Capacitor (.C)
- [x] VCCS/VCVS (.G .E)

The followings are read but not imported :
- [ ] Diode (.D)
- [ ] Bipolar Junction Transistors (.Q)
- [ ] JFET (.J)
- [ ] MOSFET (.M)
- [ ] .OPTIONS
- [ ] .NODESET
- [ ] .IC
- [ ] .AC
- [ ] .DC
- [ ] .PZ
- [ ] .SENS
- [ ] .TF
- [ ] .TRAN
- [ ] .PRINT
