### ISSUE TITLE
Possible Crash with "User defined expression" 

### ISSUE THREAD

**Issue by ghost** [aesim-tech/simba-project#421]
As a user, I have detected a possible crash once the simulation is done by using "user defined expression".
Workaround: build the math expression with SIMBA control blocks.

**Comment by manu-aesim** [comment]
We found a potential bug in the "User Defined Expression" model, which we have addressed in this preview version. @AdriPWS, could you please send it to the user to verify if the problem has been resolved?

https://aesimtech.s3.us-east-1.amazonaws.com/artifacts/Wl66vpcjs9oPPMAuio1V37txhpcQJunp/simba.exe
pip install aesim.simba==2024.4.18a1

**Comment by ghost** [comment]
Hi Manu,

Thanks for the reply..
For sure, I'm going to contact the user.

Thanks,
KR
