### ISSUE TITLE
Attribute Bug in Diode & MOSFET

### ISSUE THREAD

**Issue by anu8276** [aesim-tech/simba-project#425]
**Describe the bug**
The matrix in the detailed diode are getting displayed on the schematic screen as shown in the .gif attached

**To Reproduce**
1. Go to 'Library'
2. Click on 'Detailed Diode'
3. Scroll down to 'Voltage-Diode Current Matrix' in properties window
4. The complete matrix will be displayed on the screen

**Screensh
![AttributeBug_Diode](https://github.com/aesim-tech/simba-project/assets/115780514/d3756b0d-865c-4abf-890d-d01bca5fa451)
ots**

**Desktop (please complete the following information):**
 - OS: Wndows
 - Language: English

** SIMBA Version**
 - 24.5.2.0

**Additional context**
The same behavior is there for the existing detailed MOSFET, but can't be reproduced form the library.

**Comment by ghost** [comment]
The same thing appears for the "PWL" block "Inputs".
This happens as soon as the PWL-Input is changed and applied (via the GUI).

**Comment by manu-aesim** [comment]
Fixed in 2024.05.06
