### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by arharsha** [aesim-tech/simba-project#58]
Ability to search through various library elements via a search bar or by a tool tip on the model page will help in decreasing model development time
![Search](https://user-images.githubusercontent.com/17317006/95033307-53b84600-0683-11eb-839a-36d8ed87ba1a.jpg)

**Comment by aesim-tech** [comment]
Great Proposal Arharsha!

We have already an issue opened for the search feature (#23). I will close the other one and keep this one opened. 

The plan is to develop a unique search engine that searches in Libraries, Designs, Results, and Test Benches.
For instance, if you type "Resistor", it will show:
- The "Resistor" model in the library (to add a new "Resistor" model to the active circuit)
- Every instance of "Resistor" in the active circuit ("R1", "R2", "R3"...)
- Every chart with "Resistor" scopes
- ...

The idea is to have this search engine as reactive as possible with a nice UI you can invoke from anywhere with a shortcut. 

Let me know if you have any comments. This will be implemented in 4-6 months.

**Comment by aesim-tech** [comment]
Similar feature developed: #160
