### ISSUE TITLE
Improve Simulation Waveform Interface

### ISSUE THREAD

**Issue by aesim-tech** [aesim-tech/simba-project#71]
- [x] Keep current zoom state when the graph source is changed (new signal or simulation)
- [x] Possibility to rename a simulation results/signals
- [ ] Option to change the order of waveforms within a chart
- [x] Improve Cursor Interface
- [ ] Use S.I. Units (axis & cursor results) 
- [x] Sync FFT colours with source signals
- [x]  Add search option to filter Results
- [x] Add explanation on the "Pinned Signal Concept" 
- [x] Renamed "Instantaneous XXX" scopes by "XXX"

**Comment by ghost** [comment]
It would be also nice to save the settings (selected curves & scales) in order to recover these appearances when I re open the same circuit later
